import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = (path) => fs.readFileSync(path, 'utf8')

test('profile API routes are exposed behind authenticated Worker routing', () => {
  const routes = read('src/worker/index.ts')
  const profile = read('src/worker/profile.ts')

  assert.match(routes, /getProfile/)
  assert.match(routes, /updateProfile/)
  assert.match(routes, /changePassword/)
  assert.match(routes, /revokeSessions/)
  assert.match(routes, /deleteAccount/)
  assert.match(routes, /path === '\/api\/profile' && request\.method === 'GET'/)
  assert.match(routes, /path === '\/api\/profile' && request\.method === 'PATCH'/)
  assert.match(routes, /path === '\/api\/auth\/password\/change'/)
  assert.match(routes, /path === '\/api\/auth\/sessions\/revoke'/)
  assert.match(routes, /path === '\/api\/account' && request\.method === 'DELETE'/)
  assert.match(profile, /authIdentities/)
  assert.match(profile, /sessions/)
  assert.match(profile, /listAlbumSummaries/)
  assert.match(profile, /pageCountByAlbum/)
  assert.match(profile, /usage/)
  assert.match(profile, /albums: albumSummaries/)
})

test('auth protection stores hashed attempt data and guards sensitive auth routes', () => {
  const schema = read('src/worker/db/schema.ts')
  const security = read('src/worker/security.ts')
  const auth = read('src/worker/auth.ts')

  assert.match(schema, /authAttempts/)
  assert.match(schema, /securityEvents/)
  assert.match(schema, /subjectHash/)
  assert.match(schema, /ipHash/)
  assert.match(security, /enforceAuthProtection/)
  assert.match(security, /recordAuthAttempt/)
  assert.match(security, /verifyTurnstile/)
  assert.match(security, /RATE_LIMITED/)
  assert.match(security, /ACCOUNT_LOCKED/)
  assert.match(security, /CHALLENGE_REQUIRED/)
  assert.doesNotMatch(security, /credentialHash|passwordHash|rawPassword/)
  assert.match(auth, /enforceAuthProtection\(ctx, 'register'/)
  assert.match(auth, /enforceAuthProtection\(ctx, 'login'/)
  assert.match(auth, /enforceAuthProtection\(ctx, 'google_start'/)
  assert.match(auth, /enforceAuthProtection\(ctx, 'google_desktop_start'/)
  assert.match(auth, /enforceAuthProtection\(ctx, 'google_desktop_claim'/)
  assert.match(auth, /recordAuthAttempt\(ctx, protection/)
})

test('D1 migrations include auth protection tables and indexes', () => {
  const migration = fs.readdirSync('drizzle')
    .filter((name) => name.endsWith('.sql'))
    .map((name) => read(`drizzle/${name}`))
    .join('\n')

  assert.match(migration, /CREATE TABLE `auth_attempts`/)
  assert.match(migration, /CREATE TABLE `security_events`/)
  assert.match(migration, /auth_attempts_action_subject_created_idx/)
  assert.match(migration, /auth_attempts_action_ip_created_idx/)
  assert.match(migration, /security_events_user_created_idx/)
})

test('profile dialog is wired from the avatar menu and exposes account security views', () => {
  const userMenu = read('src/components/Auth/UserMenu.tsx')
  const dialog = read('src/components/Auth/ProfileDialog.tsx')
  const api = read('src/services/cloudflareApi.ts')

  assert.match(userMenu, /ProfileDialog/)
  assert.match(userMenu, /setShowProfileDialog\(true\)/)
  assert.match(dialog, /โปรไฟล์/)
  assert.match(dialog, /อีเมล/)
  assert.match(dialog, /รหัสผ่าน/)
  assert.match(dialog, /อัลบั้มของฉัน/)
  assert.match(dialog, /ความปลอดภัย/)
  assert.match(dialog, /revokeUserSessions/)
  assert.match(dialog, /deleteCurrentAccount/)
  assert.match(dialog, /grid-cols-\[17rem_minmax\(0,1fr\)\]/)
  assert.match(dialog, /ProfileModalNavItemActive/)
  assert.match(dialog, /AlbumSummaryList/)
  assert.match(dialog, /openAlbumById/)
  assert.match(dialog, /profile-avatar-file/)
  assert.match(dialog, /PasswordChecklist/)
  assert.match(dialog, /currentDeviceFallbackSession/)
  assert.match(dialog, /hasStoredSessions/)
  assert.doesNotMatch(dialog, /bg-\[var\(--moxzk-surface\)\]/)
  assert.doesNotMatch(dialog, /bg-\[var\(--moxzk-surface-2\)\]/)
  assert.doesNotMatch(dialog, /Secured by Moxzk/)
  assert.match(dialog, /รูปภาพ และงานที่บันทึกไว้|รูปภาพและงานที่บันทึกไว้/)
  assert.doesNotMatch(dialog, /การลบบัญชีจะลบ metadata|ไฟล์ R2|Avatar URL/)
  assert.match(api, /getProfile/)
  assert.match(api, /updateProfile/)
  assert.match(api, /changePassword/)
  assert.match(api, /revokeUserSessions/)
  assert.match(api, /deleteCurrentAccount/)
})

test('profile product copy rules are recorded for future agents', () => {
  const rootGuide = read('AGENTS.md')
  const agentGuide = read('.agents/AGENTS.md')

  assert.match(rootGuide, /Product Language/)
  assert.match(rootGuide, /ordinary users/)
  assert.match(rootGuide, /avoid implementation terms/)
  assert.match(agentGuide, /ordinary users/)
  assert.match(agentGuide, /User-facing copy/)
})

test('profile and auth protection docs describe Cloudflare edge responsibilities', () => {
  const docs = read('docs/auth-profile-security.md')

  assert.match(docs, /ProfileDialog/)
  assert.match(docs, /Cloudflare WAF/)
  assert.match(docs, /rate-limit/)
  assert.match(docs, /Turnstile/)
  assert.match(docs, /DDoS/)
  assert.match(docs, /auth_attempts/)
})
