import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

test('Moxzk rename keeps legacy aliases for local data and auth transition', () => {
  const appIdentity = fs.readFileSync('src/config/appIdentity.ts', 'utf8')
  const settingsStorage = fs.readFileSync('src/services/settingsStorage.ts', 'utf8')
  const imageCache = fs.readFileSync('src/services/imageCache.ts', 'utf8')
  const fontStorage = fs.readFileSync('src/services/fontStorage.ts', 'utf8')
  const translationMemory = fs.readFileSync('src/services/translationMemory.ts', 'utf8')
  const projectDraftStorage = fs.readFileSync('src/services/projectDraftStorage.ts', 'utf8')
  const desktopDraftCodec = fs.readFileSync('src/runtime/desktopDraftCodec.ts', 'utf8')
  const workerAuth = fs.readFileSync('src/worker/auth.ts', 'utf8')
  const wranglerConfig = fs.readFileSync('wrangler.jsonc', 'utf8')

  assert.match(appIdentity, /APP_DISPLAY_NAME = 'Moxzk'/)
  assert.match(appIdentity, /LEGACY_APP_DISPLAY_NAME = 'MG Translater'/)
  assert.match(appIdentity, /SESSION_COOKIE_NAME = 'moxzk_session'/)
  assert.match(appIdentity, /LEGACY_SESSION_COOKIE_NAME = 'mg_session'/)
  assert.match(settingsStorage, /SETTINGS_KEY = 'moxzk-settings'/)
  assert.match(settingsStorage, /LEGACY_SETTINGS_KEY = 'mg-translater-settings'/)
  assert.match(imageCache, /DB_NAME = 'moxzk-cache'/)
  assert.match(imageCache, /LEGACY_DB_NAME = 'mg-translater-cache'/)
  assert.match(fontStorage, /DB_NAME = 'moxzk-fonts'/)
  assert.match(fontStorage, /LEGACY_DB_NAME = 'mg-translater-fonts'/)
  assert.match(translationMemory, /DB_NAME = 'moxzk-translation-memory'/)
  assert.match(translationMemory, /LEGACY_DB_NAME = 'mg-translation-memory'/)
  assert.match(projectDraftStorage, /DB_NAME = 'moxzk-project-drafts'/)
  assert.match(projectDraftStorage, /LEGACY_DB_NAME = 'mg-project-drafts'/)
  assert.match(desktopDraftCodec, /ASSET_URL_PREFIX = 'moxzk-asset:\/\/'/)
  assert.match(desktopDraftCodec, /LEGACY_ASSET_URL_PREFIX = 'mg-asset:\/\/'/)
  assert.match(workerAuth, /X-Moxzk-Desktop-Auth-Origin/)
  assert.match(workerAuth, /X-MG-Desktop-Auth-Origin/)
  assert.match(wranglerConfig, /moxzk:\/\/auth\/callback/)
  assert.match(wranglerConfig, /mg-translater:\/\/auth\/callback/)
})
