import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = fs.readFileSync('src/components/Settings/SettingsPanel.tsx', 'utf8')
const css = fs.readFileSync('src/index.css', 'utf8')
const settingsStorage = fs.readFileSync('src/services/settingsStorage.ts', 'utf8')
const appSource = fs.readFileSync('src/App.tsx', 'utf8')

test('settings modal is sized as a desktop workspace', () => {
  assert.match(source, /SettingsWorkspace/)
  assert.match(source, /max-w-6xl/)
  assert.match(source, /h-\[min\(84vh,820px\)\]/)
  assert.match(css, /\.SettingsWorkspace/)
  assert.match(css, /max-width: min\(72rem, calc\(100vw - 3rem\)\) !important/)
})

test('settings keeps Ollama setup compact', () => {
  assert.match(source, /AI แปลภาษา/)
  assert.match(source, /<ExternalLink size=\{12\} \/> ดาวน์โหลด/)
  assert.match(source, /https:\/\/ollama\.com\/download\/windows/)
  assert.match(source, /name: 'gemma3:4b'/)
  assert.match(source, /`ollama pull \$\{model\}`/)
  assert.match(source, /function describeOllamaSummary/)
  assert.match(source, /const canStartOllamaService = canStartOllama && !ollamaReady && !localServiceStatus\.ollama\.running/)
  assert.match(source, /const canPullOllamaModel = !isOllamaCloud && Boolean\(selectedModelName\) && !pullingModel/)
  assert.match(source, /const selectedModelKnown = Boolean\(selectedModelName\) && installedModels\.has\(selectedModelName\)/)
  assert.match(source, /const visibleModelNames = useMemo/)
  assert.match(source, /const showModelNotListedHint = Boolean\(selectedModelName\) && modelNames\.length > 0 && !selectedModelKnown && !selectedModelIsPulling/)
  assert.match(source, /const refreshOllamaModels = useCallback/)
  assert.match(source, /if \(!isOpen \|\| tab !== 'models'\) return/)
  assert.match(source, /void refreshOllamaModels\(\)/)
  assert.match(source, /const handleLoadModels = \(\) => refreshOllamaModels\(\{ notify: true \}\)/)
  assert.match(source, /visibleModelNames\.slice\(0, 4\)/)
  assert.match(source, /ค่าที่บันทึกไว้/)
  assert.match(source, /function ModelPullProgress/)
  assert.match(source, /aria-pressed=\{active\}/)
  assert.match(source, /settings-model-preset-active/)
  assert.match(source, /โมเดลนี้ยังไม่อยู่ในรายชื่อที่รีเฟรชล่าสุด/)
  assert.match(source, /ถ้าชื่อโมเดลผิดให้แก้ชื่อ/)
  assert.match(source, /โหลดเข้า Ollama/)
  assert.match(source, /โมเดลจะอยู่ในที่เก็บของ Ollama ไม่อยู่ในโฟลเดอร์ Moxzk/)
  assert.match(source, /เหมือนคำสั่ง ollama pull/)
  assert.match(source, /คัดลอกคำสั่ง/)
  assert.match(css, /\.settings-model-progress/)
  assert.match(css, /\.settings-model-preset-active/)
  assert.doesNotMatch(source, /ติดตั้งในเครื่องนี้/)
  assert.doesNotMatch(source, /โหลดโมเดล/)
  assert.doesNotMatch(source, /คู่มือเริ่มต้น/)
  assert.doesNotMatch(source, /สถานะในเครื่อง/)
})

test('settings keeps translation guidance separate from model setup', () => {
  assert.match(source, /type SettingsTab = 'general' \| 'models' \| 'translation' \| 'cleanup' \| 'about'/)
  assert.match(source, /ใช้บริบทข้ามหน้า/)
  assert.match(source, /โหมดคำแปล/)
  assert.match(source, /สั้นเข้าใจได้/)
  assert.match(source, /ตรงตามต้นฉบับ/)
  assert.match(source, /translationMode/)
  assert.match(settingsStorage, /translationMode: settings\.translationMode/)
  assert.match(settingsStorage, /normalizeTranslationMode/)
  assert.match(source, /ไกด์โทนคำแปล/)
  assert.match(source, /rows=\{9\}/)
})

test('settings exposes about and licensing boundaries', () => {
  assert.match(source, /label: 'เกี่ยวกับ'/)
  assert.match(source, /APP_LICENSE_NAME = 'MIT'/)
  assert.match(source, /https:\/\/magga\.vercel\.app/)
  assert.match(source, /เปิดให้ใช้และปรับแก้ตัวโปรแกรมได้ภายใต้ MIT/)
  assert.match(source, /สิ่งที่ใช้ร่วมกัน/)
  assert.match(source, /ตัวช่วยลบข้อความใช้ PanelCleaner แยกจากตัวโปรแกรมหลัก/)
  assert.match(source, /Ollama, Ollama Cloud และโมเดลที่เลือกใช้/)
  assert.match(source, /รูปภาพ อัลบั้ม งานร่าง ไฟล์ที่นำเข้า และไฟล์ที่ส่งออก/)
  assert.match(source, /settings-about-summary/)
  assert.match(source, /settings-about-list/)
  assert.match(source, /aria-current=\{tab === id \? 'page' : undefined\}/)
  assert.doesNotMatch(source, /source code/)
  assert.doesNotMatch(source, /external GPLv3 dependency/)
  assert.doesNotMatch(source, /ไฟล์ใน repo/)
  assert.doesNotMatch(source, /NOTICE\.md/)
  assert.doesNotMatch(source, /function StatusTile/)
  assert.doesNotMatch(source, /function NoticeCard/)
})

test('settings cleanup summary prefers working PanelCleaner bridge status', () => {
  assert.match(source, /function describePanelCleanerSummary/)
  assert.match(source, /bridgeStatus\?\.ok/)
  assert.match(source, /พร้อมใช้งานจาก\$\{panelCleanerSourceText\(bridgeStatus\)\}/)
  assert.match(source, /const panelCleanerReady = panelCleanerStatus\?\.ok \|\| panelCleanerDependency\?\.state === 'ready'/)
  assert.match(source, /const canInstallPanelCleaner = canStartPanelCleaner && !panelCleanerReady/)
  assert.match(source, /const canStartPanelCleanerBridge = canStartPanelCleaner && !localServiceStatus\.panelcleaner\.running/)
})

test('settings cleanup errors do not tell users to reopen the same settings page', () => {
  const panelCleanerClient = fs.readFileSync('src/services/panelcleaner-api.ts', 'utf8')
  const bridge = fs.readFileSync('scripts/panelcleaner-bridge.mjs', 'utf8')
  const parseApiError = fs.readFileSync('src/utils/parseApiError.ts', 'utf8')

  assert.match(source, /function describePanelCleanerFailure/)
  assert.match(source, /ตัวช่วยยังไม่เปิด · กดเริ่ม PanelCleaner ก่อน/)
  assert.match(source, /ยังไม่พบชุด PanelCleaner ที่ใช้งานได้ · กดติดตั้ง PanelCleaner หรือเลือกไฟล์เอง/)
  assert.doesNotMatch(panelCleanerClient, /เปิด Settings > ลบข้อความ/)
  assert.doesNotMatch(parseApiError, /เปิด Settings > ลบข้อความ/)
  assert.doesNotMatch(bridge, /Open Settings > Cleanup/)
})

test('toast notifications stay above settings modal layer', () => {
  assert.match(appSource, /function AppToaster/)
  assert.match(appSource, /createPortal\(/)
  assert.match(appSource, /document\.body/)
  assert.match(appSource, /<Toaster/)
  assert.match(appSource, /position="bottom-right"/)
  assert.match(appSource, /className="moxzk-toaster"/)
  assert.match(appSource, /style=\{\{ zIndex: 1000 \}\}/)
  assert.match(appSource, /toastOptions=\{\{/)
  assert.doesNotMatch(appSource, /className: 'mt-12'/)
})
