#!/usr/bin/env python3
"""Generate a compact repository tree for the .agents context layer."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


DEFAULT_EXCLUDES = {
    ".agents/skills",
    ".claude/skills",
    ".git",
    ".next",
    ".venv",
    ".venv-panelcleaner",
    ".vercel",
    ".wrangler",
    "_codex",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "graphify-out",
    "node_modules",
    "output",
    "skills",
    "test-results",
}

DEFAULT_FILE_EXCLUDES = {
    ".dev.vars",
    ".env",
    ".env.local",
    "package-lock.json",
}

DEFAULT_SUFFIX_EXCLUDES = {
    ".log",
    ".pem",
    ".pyc",
    ".tsbuildinfo",
}


def normalize(path: Path) -> str:
    return path.as_posix()


def should_exclude(path: Path, root: Path) -> bool:
    rel = normalize(path.relative_to(root))
    name = path.name

    if rel in DEFAULT_EXCLUDES or name in DEFAULT_EXCLUDES:
        return True

    if path.is_file():
        if name in DEFAULT_FILE_EXCLUDES:
            return True
        if any(name.endswith(suffix) for suffix in DEFAULT_SUFFIX_EXCLUDES):
            return True

    return any(part in DEFAULT_EXCLUDES for part in path.parts)


def iter_children(path: Path, root: Path) -> list[Path]:
    children = [child for child in path.iterdir() if not should_exclude(child, root)]
    return sorted(children, key=lambda child: (child.is_file(), child.name.lower()))


def render_tree(root: Path, max_depth: int) -> list[str]:
    lines = [f"# Repository Tree", "", f"Root: `{root.name}`", "", "```text", "."]

    def walk(directory: Path, prefix: str, depth: int) -> None:
        if depth >= max_depth:
            return

        children = iter_children(directory, root)
        for index, child in enumerate(children):
            is_last = index == len(children) - 1
            branch = "`-- " if is_last else "|-- "
            suffix = "/" if child.is_dir() else ""
            lines.append(f"{prefix}{branch}{child.name}{suffix}")

            if child.is_dir():
                extension = "    " if is_last else "|   "
                walk(child, prefix + extension, depth + 1)

    walk(root, "", 0)
    lines.append("```")
    lines.append("")
    lines.append("Generated by `scripts/update_repo_context.py`.")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root to scan.")
    parser.add_argument(
        "--output",
        default=".agents/index/repo-tree.md",
        help="Markdown file to write.",
    )
    parser.add_argument("--max-depth", type=int, default=5, help="Maximum tree depth.")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output = Path(args.output)
    if not output.is_absolute():
        output = root / output

    if not root.exists() or not root.is_dir():
        raise SystemExit(f"Root is not a directory: {root}")

    output.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(render_tree(root, args.max_depth)) + "\n"
    output.write_text(content, encoding="utf-8", newline="\n")

    relative_output = os.path.relpath(output, root)
    print(f"Wrote {relative_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
