export const IPC_CHANNELS = {
  filesSaveFile: 'runtime:files.saveFile',
  filesSaveExportFiles: 'runtime:files.saveExportFiles',
  projectDraftSave: 'runtime:projectDraft.save',
  projectDraftLoad: 'runtime:projectDraft.load',
  projectDraftClear: 'runtime:projectDraft.clear',
  localServicesStartPanelCleanerBridge: 'runtime:localServices.startPanelCleanerBridge',
  localServicesStartOllama: 'runtime:localServices.startOllama',
  localServicesBeginUsage: 'runtime:localServices.beginUsage',
  localServicesEndUsage: 'runtime:localServices.endUsage',
  localServicesGetManagedStatus: 'runtime:localServices.getManagedStatus',
  localServicesPanelCleanerDependencyStatus: 'runtime:localServices.panelCleanerDependencyStatus',
  localServicesInstallPanelCleaner: 'runtime:localServices.installPanelCleaner',
  localServicesRepairPanelCleaner: 'runtime:localServices.repairPanelCleaner',
  localServicesPickPanelCleanerExecutable: 'runtime:localServices.pickPanelCleanerExecutable',
  localServicesStopOwnedServices: 'runtime:localServices.stopOwnedServices',
  authSignInWithGoogle: 'runtime:auth.signInWithGoogle',
  windowControlsMinimize: 'runtime:windowControls.minimize',
  windowControlsToggleMaximize: 'runtime:windowControls.toggleMaximize',
  windowControlsClose: 'runtime:windowControls.close',
  windowControlsGetState: 'runtime:windowControls.getState',
  windowControlsStateChanged: 'runtime:windowControls.stateChanged',
} as const
